repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args: ['--branch', 'main']

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-java
        args: [--autofix]
        files: \.java$

  - repo: local
    hooks:
      - id: spotless-check
        name: Spotless Check
        entry: ./gradlew spotlessCheck
        language: system
        pass_filenames: false
        types: [java]

      - id: gradle-check
        name: Gradle Check
        entry: ./gradlew check
        language: system
        pass_filenames: false
        types: [java] 