spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_template_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dev_user
    password: dev_password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.daejoeng: DEBUG

springdoc:
  swagger-ui:
    enabled: true 